
//Start the game
POST http://localhost:8080/

###
// Make a move
PUT http://localhost:8080/move
Content-Type: application/json

{
    "row" : 2,
    "column" : 0
}

###

// Get board
GET http://localhost:8080/

###

// Get status of the game
GET http://localhost:8080/status

